### ISSUE TITLE
Unable to fetch data from CISA.

### ISSUE THREAD

**Issue by bakhtawarw** [aleprada/PyMISP_CISA_alerts#1]
Hi, I am unable to fetch any threat data from Cisa. I always get the following output:

![image](https://user-images.githubusercontent.com/104062347/170970338-718cf643-855f-43e0-9740-836b5d06f538.png)
 
Software.txt consists of following keyword:
![image](https://user-images.githubusercontent.com/104062347/170970547-8049379f-b441-48a9-8d4e-8358d6964766.png)

MISP config is as follows:
![image](https://user-images.githubusercontent.com/104062347/170970691-abc920e2-9c41-4cca-a371-6ffb3913360c.png)

I checked the latest Cisa Advisories, there are threats related to my keyword (i.e. in software.txt) but still the output shows that there are no new threats or vulnerabilities.
![image](https://user-images.githubusercontent.com/104062347/170971576-7a1950dc-f3a3-4f97-93a6-f7e0641ccf3f.png)

**Comment by aleprada** [comment]
Hi!! 
Check the entries.db SQLite file in the config folder. I created that SQLITE file to quickly check if a threat was already gathered. If it's already stored it won't be printed nor sent to MISP.

Remove the registers, and rerun it. Take also this into account for the future if you run this periodically.

**Comment by bakhtawarw** [comment]
Hi, I have cleared the Database, but now I am getting this error.

![image](https://user-images.githubusercontent.com/104062347/171166740-9cbf0914-3f36-4608-94ae-ca28d6a6ef01.png)

**Comment by aleprada** [comment]
Hi bakhtawarw,

I've just tested the script and it works fine. The only thing that I see different is that I'm using Python 3.6 and my pymisp version is 2.4.141.1. You are using  Python 3.8 and your pymisp is 2.4.157.

Try to create a virtualenv with Python 3.6, install the requirements.txt file with the same versions and you should be Ok. Another option is to capture that NewEventError Exception, but I couldn't reproduce it.

**Comment by bakhtawarw** [comment]
Hi, I created a virtualenv with Python 3.6 and installed the requirements.txt file. But still I'm getting the following error.
![image](https://user-images.githubusercontent.com/104062347/171391350-580bb73e-03b0-437d-afa1-169de0b23087.png)
![image](https://user-images.githubusercontent.com/104062347/171391437-42c7676d-ad34-4394-9433-974022f65648.png)

**Comment by aleprada** [comment]
Hi!! It seems you have a MISP instance version that is not compatible with your pymisp library. I didn't test it with a new version yet. 

Anyway, I've just uploaded some changes for managing the exception. Could you test it with the new changes?

Thanks!

**Comment by bakhtawarw** [comment]
Hi, I tested it with changes. Still doesn't work.
![image](https://user-images.githubusercontent.com/104062347/171589435-5e283ba3-b938-444c-9688-63fb82fc2215.png)


P.s: What's the version of your MISP instance?

**Comment by aleprada** [comment]
Try it again, I've updated the cast to string when printing the exception.

I tested the script successfully with the 2.4.150 version.

**Comment by bakhtawarw** [comment]
Hi, I am getting these errors now. Also, do I have to make any changes in the project except adding Misp Url and API key in config.ini file? 
The methodology I followed was to create a virtual environment, clone the project and install requirements.txt file. Then added Misp Url and API key in config.ini file. And used the command "python3 main.py --full" to run the project. Is there anything which I am missing ?

![image](https://user-images.githubusercontent.com/104062347/171599970-92919ba2-ace8-4873-b7c8-b855290b721b.png)

**Comment by aleprada** [comment]
Probably it cannot find the package. Try "python setup.py install" within your virtualenv.

**Comment by bakhtawarw** [comment]
Hi, I tried "python setup.py install" but still getting the same error. Anything else that you would suggest to make it work?

**Comment by aleprada** [comment]
Hi there!

Did you solve your issues? I've been out from home for a week and I couldn't answer you before. I uploaded a Dockerfile that may help you to test the script.

docker build -t cisa_test .
docker run -it cisa_test

**Comment by bakhtawarw** [comment]
Hey, the issues got resolved and it works perfectly now. I did few changes in misp.py file that helped to resolve the errors.
